name: node_auth
description: Simple auth app flutter, server node.js, BLoC pattern, RxDart.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.3

  path: ^1.6.4
  http: ^0.12.0+4
  built_value: ^7.1.0
  tuple: ^1.0.3
  rxdart: ^0.24.0
  image_picker: ^0.6.5+2
  shared_preferences: ^0.5.7

  # my packages
  distinct_value_connectable_stream: ^1.1.1
  flutter_provider: ^1.1.1
  rx_shared_preferences: ^1.2.0
  disposebag: ^1.1.2
  flutter_bloc_pattern: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
  assets:
   - assets/bg.jpg
   - assets/user.png
