name: node_auth
description: Simple auth app flutter, server node.js, BLoC pattern, RxDart.

publish_to: 'none'
version: 3.0.0+3

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.3

  path: ^1.8.0
  http: ^0.13.3
  built_value: ^8.0.6
  tuple: ^2.0.0
  rxdart: ^0.27.1
  image_picker: ^0.8.0+3
  shared_preferences: ^2.0.6
  octo_image: ^1.0.0+1

  distinct_value_connectable_stream: ^1.3.0
  flutter_provider: ^2.0.0
  rx_shared_preferences: ^2.1.0
  disposebag: ^1.5.0
  flutter_disposebag: ^1.1.0
  flutter_bloc_pattern: ^2.1.1
  rxdart_ext: ^0.1.1-dev.0
  did_change_dependencies: ^1.0.0
  pedantic: ^1.11.0

dev_dependencies:
  plugin_platform_interface: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  built_value_generator: ^8.0.6

dependency_overrides:
  rxdart_ext:
    git:
      url: https://github.com/hoc081098/rxdart_ext.git
      ref: 61ab80610903916556d8f2cf9d0055c23f05bb91

flutter:
  uses-material-design: true
  assets:
   - assets/bg.jpg
   - assets/user.png
