name: node_auth
description: Simple auth app flutter, server node.js, BLoC pattern, RxDart.

publish_to: 'none'
version: 3.3.0+8

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  cupertino_http: ^0.0.7
  meta: ^1.7.0
  path: ^1.8.1
  http: ^0.13.5
  built_value: ^8.4.1
  tuple: ^2.0.0
  rxdart: ^0.27.5
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  octo_image: ^1.0.2

  flutter_provider: ^2.1.0
  rx_shared_preferences: ^3.0.0
  disposebag: ^1.5.1
  flutter_disposebag: ^1.1.0
  flutter_bloc_pattern: ^2.3.0
  rxdart_ext: ^0.2.6
  did_change_dependencies: ^1.0.0
  stream_loader: ^1.5.0
  dart_either: ^1.0.0
  http_client_hoc081098:
  cancellation_token_hoc081098: ^1.0.0

dev_dependencies:
  plugin_platform_interface: ^2.1.2
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  built_value_generator: ^8.4.1
  analyzer: ^4.6.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/bg.jpg
    - assets/user.png

dependency_overrides:
  http_client_hoc081098:
    git:
      url: https://github.com/hoc081098/http_client_hoc081098.git
      ref: e5b9d29d216bee0601783dace15850170dcbeb94
